name: 'google_ads'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=0.20.0"]
models:
  google_ads:
    +schema: google_ads
    +materialized: table
vars:
  google_ads:
    click_performance: "{{ ref('stg_google_ads__click_performance') }}"
    final_url_performance: "{{ ref('stg_google_ads__final_url_performance') }}"
    criteria_performance: "{{ ref('stg_google_ads__criteria_performance') }}"
  google_ads__url_passthrough_metrics: []
  google_ads__criteria_passthrough_metrics: []
